USE [bsbd_kursach]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [IX_Tags_Title]    Script Date: 26.03.2024 20:25:13 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Tags_Title] ON [dbo].[Tags]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
